DROP VIEW vw_TasksWithOrderForEwo
GO
CREATE VIEW vw_TasksWithOrderForEwo AS
SELECT 
    RANK() OVER(PARTITION BY MW.PROC_INST_ID ORDER BY ISNULL(MW.ASSIGNED_DATE, MW.CREATED_DATE) ASC) TaskNum, 
	ROW_NUMBER() OVER(PARTITION BY MW.PROC_INST_ID, AI.DISPLAY_NAME, MW.STATUS ORDER BY ISNULL(MW.ASSIGNED_DATE, MW.CREATED_DATE) ASC) ApproverNum, 
    MW.PROC_INST_ID, 
    AI.DISPLAY_NAME, 
    CASE
		WHEN AI.DISPLAY_NAME = 'Requestor' THEN 'Requestor'
		WHEN AI.DISPLAY_NAME = 'Approval Managers' THEN 'Manager'
		WHEN AI.DISPLAY_NAME = 'Engineering Responsible' THEN 'Engineer'
		WHEN AI.DISPLAY_NAME = 'Review' THEN 'Approver'
		WHEN AI.DISPLAY_NAME = 'CAD Supervisor' THEN 'Manager'
		WHEN AI.DISPLAY_NAME = 'Design Engineering Manager' THEN 'Manager'
		WHEN AI.DISPLAY_NAME = 'Casting Simulation Supervisor' THEN 'Manager'
		WHEN AI.DISPLAY_NAME = 'Tool Room Superintendent' THEN 'Manager'
		WHEN AI.DISPLAY_NAME = 'Engineering Manager' THEN 'Engineer'
		WHEN AI.DISPLAY_NAME = 'Return To Requestor' THEN 'Manager'
		ELSE AI.DISPLAY_NAME
	END TaskLevel,
    MW.STATUS, 
    ISNULL(MW.ASSIGNED_DATE, MW.CREATED_DATE) AS ASSIGNED_DATE,
    MW.USER_ID,
    RU.FULL_NAME,
    RU.EMAIL_ADDRESS,
    PI.PROC_INST_NAME,
    PI.STARTED_DATE
FROM APDB.dbo.WF_MANUAL_WORKITEMS MW
LEFT JOIN APDB.dbo.WF_ACTIVITY_INSTS AI ON AI.ID = MW.ACTIVITY_INST_ID
LEFT JOIN APDB.dbo.WF_REG_USERS RU ON RU.USER_NAME = MW.USER_ID
LEFT JOIN APDB.dbo.WF_PROC_INSTS PI ON MW.PROC_INST_ID = PI.PROC_INST_ID
GO