DROP VIEW vw_TasksWithOrderForEwo
GO
CREATE VIEW vw_TasksWithOrderForEwo AS
SELECT 
    ROW_NUMBER() OVER(PARTITION BY MW.PROC_INST_ID ORDER BY MW.ASSIGNED_DATE) TaskNum, 
    MW.PROC_INST_ID, 
    AI.DISPLAY_NAME, 
    MW.STATUS, 
    MW.ASSIGNED_DATE, 
    MW.USER_ID,
    RU.FULL_NAME,
    RU.EMAIL_ADDRESS,
    PI.PROC_INST_NAME,
    PI.STARTED_DATE
FROM APDB.dbo.WF_MANUAL_WORKITEMS MW
LEFT JOIN APDB.dbo.WF_ACTIVITY_INSTS AI ON AI.ID = MW.ACTIVITY_INST_ID
LEFT JOIN APDB.dbo.WF_REG_USERS RU ON RU.USER_NAME = MW.USER_ID
LEFT JOIN APDB.dbo.WF_PROC_INSTS PI ON MW.PROC_INST_ID = PI.PROC_INST_ID
GO