SELECT
	D.DocumentID__u 'Document',
	MCC.MCCCode__u 'MCC',
	MCC.NewValue__u - MCC.OldValue__u 'MCC Input',
	MCC.OldValue__u 'MCC Old Value',
	MCC.NewValue__u 'MCC New Value',
	MCC.Comment__u 'MCC Comment',
	UMCC.FULL_NAME 'MCC User',
	CONVERT(VARCHAR(20), CONVERT(DATETIME, MCC.CREATED_DATE), 101) + ' ' + CONVERT(VARCHAR(20), CONVERT(DATETIME, MCC.CREATED_DATE), 108) 'MCC Date',
	CONVERT(DATETIME, MCC.CREATED_DATE) 'MCC Date Hdn'
FROM EWOMccAudit__u MCC
LEFT JOIN EWOFormData__u D ON D.ID = MCC.EwoFdID__u
LEFT JOIN APDB.dbo.WF_REG_USERS UMCC ON UMCC.USER_NAME = MCC.CREATED_BY